# Generated by Django 6.0.7 on 2026-08-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0002_sitesettings_services_background_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('date', models.DateField(unique=True, verbose_name='Недоступная дата')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Заблокирована')),
            ],
            options={
                'verbose_name': 'Недоступная дата',
                'verbose_name_plural': 'Недоступные даты',
                'ordering': ['date'],
            },
        ),
    ]
