# Generated by Django 6.0.7 on 2026-08-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0003_blockeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='available_dates_background',
            field=models.ImageField(blank=True, null=True, upload_to='site/available_dates/', verbose_name='Фон страницы свободных дат'),
        ),
    ]
