# Generated by Django 6.0.7 on 2026-08-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0004_sitesettings_available_dates_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='booking_photographer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='site/booking/', verbose_name='Фотография фотографа на странице записи'),
        ),
    ]
