# Generated by Django 6.0.7 on 2026-08-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0005_sitesettings_booking_photographer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio_1.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Фотография услуги',
                'verbose_name_plural': 'Фотографии услуг',
                'ordering': ['order', 'id'],
            },
        ),
    ]
