# Generated by Django 6.0.7 on 2026-08-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0006_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_bottom_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/portfolio/', verbose_name='Фотография в нижней секции портфолио'),
        ),
    ]
