# Generated by Django 6.0.7 on 2026-08-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0007_sitesettings_portfolio_bottom_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feature_slider/', verbose_name='Фотография')),
                ('subtitle_ru', models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок (RU)')),
                ('subtitle_en', models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок (EN)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('link_text_ru', models.CharField(blank=True, max_length=120, verbose_name='Текст ссылки (RU)')),
                ('link_text_en', models.CharField(blank=True, max_length=120, verbose_name='Текст ссылки (EN)')),
                ('link_url', models.CharField(blank=True, help_text='Можно указать обычный URL, например /booking/ или https://example.com', max_length=500, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Слайд нижнего блока',
                'verbose_name_plural': 'Слайды нижнего блока',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='portfolio_bottom_image',
        ),
    ]
