# Generated by Django 6.0.7 on 2026-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0008_featureslide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_background',
            field=models.ImageField(blank=True, null=True, upload_to='site/reviews/', verbose_name='Фон блока отзывов'),
        ),
    ]
