# Generated by Django 6.0.7 on 2026-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0009_sitesettings_reviews_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='available_dates_background',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='available_dates_cta_background',
            field=models.ImageField(blank=True, null=True, upload_to='site/available_dates/', verbose_name='Фон нижнего блока свободных дат'),
        ),
    ]
