# Generated by Django 6.0.7 on 2026-08-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0010_remove_sitesettings_available_dates_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureslide',
            name='image',
            field=models.ImageField(max_length=500, null=True, upload_to='feature_slider/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='image_desktop',
            field=models.ImageField(max_length=500, null=True, upload_to='slides/desktop/', verbose_name='Изображение для компьютера'),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='image_mobile',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='slides/mobile/', verbose_name='Изображение для телефона'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=500, null=True, upload_to='portfolio/photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='portfolio/thumbnails/', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='cover',
            field=models.ImageField(max_length=500, null=True, upload_to='portfolio/covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='cover_mobile',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='portfolio/covers/mobile/', verbose_name='Обложка для телефона'),
        ),
        migrations.AlterField(
            model_name='review',
            name='client_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='reviews/', verbose_name='Фотография клиента'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='services/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(max_length=500, null=True, upload_to='services/gallery/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='available_dates_cta_background',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='site/available_dates/', verbose_name='Фон нижнего блока свободных дат'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='booking_photographer_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='site/booking/', verbose_name='Фотография фотографа на странице записи'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='site/logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='photographer_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='site/photographer/', verbose_name='Фотография фотографа'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='reviews_background',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='site/reviews/', verbose_name='Фон блока отзывов'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='services_background',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='site/services/', verbose_name='Фон страницы услуг'),
        ),
    ]
