# Generated by Django 6.0.7 on 2026-09-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0011_alter_featureslide_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='coupon_active',
            field=models.BooleanField(default=False, verbose_name='Показывать купон'),
        ),
        migrations.AddField(
            model_name='service',
            name='coupon_text',
            field=models.CharField(blank=True, help_text='Например: Скидка 10% или -15% на первую съёмку', max_length=100, verbose_name='Купон'),
        ),
    ]
