# Generated by Django 6.0.7 on 2026-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0012_service_coupon_active_service_coupon_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='coupon_text',
        ),
        migrations.AddField(
            model_name='service',
            name='coupon_text_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Текст купона на английском'),
        ),
        migrations.AddField(
            model_name='service',
            name='coupon_text_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Текст купона на русском'),
        ),
    ]
